# Generated by Django 4.1.7 on 2023-03-18 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('photo_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_of_release', models.DateField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(max_length=15)),
                ('starring', models.CharField(max_length=500)),
                ('summary', models.TextField(max_length=500)),
                ('poster_url', models.CharField(max_length=200)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dir_app.director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dir_app.genre')),
            ],
        ),
    ]
